name: Build Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install glib-compile-schemas
        run: sudo apt-get install -y --no-install-recommends libglib2.0-bin

      - name: Build zip
        run: make

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: one-thing@github.com
          path: one-thing@github.com.zip
          retention-days: 1
