name: Build Extension

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install glib-compile-schemas
        run: sudo apt-get install -y --no-install-recommends libglib2.0-bin

      - name: Build bundle directory
        run: make bundle-dir

      - name: Analyse with shexli
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -U shexli
          shexli bundle/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: one-thing@github.com
          path: bundle/
          retention-days: 1
